from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional, Tuple

class IOrderRepository(ABC):
    @abstractmethod
    def add(self, client: str, items_str: str, total: float, status: str, date: str, client_type: str) -> int: ...
    @abstractmethod
    def get(self, order_id: int) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    def update_status(self, order_id: int, status: str) -> None: ...
    @abstractmethod
    def get_all_by_client(self, client: str) -> List[Tuple[Any, ...]]: ...
    @abstractmethod
    def get_all(self) -> List[Tuple[Any, ...]]: ...
    @abstractmethod
    def get_all_clients(self) -> List[Tuple[Any, ...]]: ...
    @abstractmethod
    def close(self) -> None: ...

class IDiscountStrategy(ABC):
    @abstractmethod
    def calculate(self, items: List[Dict[str, Any]], client_type: str) -> float: ...

class IPaymentStrategy(ABC):
    @abstractmethod
    def process(self, amount: float) -> bool: ...

class IOrderObserver(ABC):
    @abstractmethod
    def update(self, order_id: int, client: str, client_type: str, status: str, total: float) -> None: ...